server:
  port: 8080
spring:
  application:
    name: mall
  datasource:
      username: root
      password: zzt182052
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mall?serverTimezone=GTM%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
mybatis:
  #指定mapper.xml的位置
  mapper-locations: mybatis/mapper/*.xml
